sudo: required
services:
  - docker
before_install: 
  - openssl aes-256-cbc -K $encrypted_4491bbd041e7_key -iv $encrypted_4491bbd041e7_iv -in multi-k8s-348609-28ed82e4ae1c.json.enc -out multi-k8s-348609-28ed82e4ae1c.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  
